-- 코드를 입력하세요
SELECT SALE.USER_ID
     , SALE.PRODUCT_ID
  FROM ONLINE_SALE SALE
  GROUP BY SALE.USER_ID, SALE.PRODUCT_ID
  HAVING COUNT(SALE.PRODUCT_ID) >= '2'
  ORDER BY USER_ID ASC, PRODUCT_ID DESC

 # SELECT * FROM ONLINE_SALE SALE ORDER BY USER_ID